name: Build and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Python script
        run: python3 ./CdnSender/mod_sender.py
        env:
          PRICECXNAUTH: ${{ secrets.PRICECXNAUTH }}
