name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Python script
        run: python3 /opt/actions-runner/mod_poster.py
        env:
          PRICECXNAUTH: ${{ secrets.PRICECXNAUTH }}
